export const roleData = {
  dashboard: {
    view: false,
    viewCasesCounts: false,
    viewTurnAroundTimeMetrics: false,
    viewInvestigators: false,
    viewUsers: false,
    viewYearWiseCaseGrowth: false,
    viewTopServices: false,
    viewTopCompanies: false,
    viewCurrentYearMonthWiseCases: false,
    viewIncomeVsExpense: false,
    viewTopInvestigators: false,
    viewCases: false,
  },
  system: {
    view: false,
    role: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    user: {
      view: false,
      add: false,
      edit: false,
      delete: false,

      userDetails: {
        view: false,
        edit: false,
      },
      services: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      charges: {
        view: false,
        edit: false,
      },
      subInvestigators: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      changePassword: {
        view: false,
        edit: false,
      },
    },
    userType: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    employmentType: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    designation: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    investigatorType: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
  },
  masters: {
    view: false,
    vertical: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    service: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    investigationService: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    caseStatus: {
      view: false,
      edit: false,
    },
    claimType: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    investigationType: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    hospital: {
      view: false,
      add: false,
      edit: false,
      delete: false,
      hospitalDetails: {
        view: false,
        edit: false,
      },
      facilities: {
        view: false,
        edit: false,
      },
      pathologist: {
        view: false,
        edit: false,
      },
      medicalStore: {
        view: false,
        edit: false,
      },
      tariff: {
        view: false,
        edit: false,
      },
      insuranceCompany: {
        view: false,
        edit: false,
      },
    },
    doctor: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    pathologist: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    insuranceCompanies: {
      view: false,
      add: false,
      edit: false,
      delete: false,
      companyDetail: {
        view: false,
        edit: false,
      },
      service: {
        view: false,
        add: false,
        edit: false,
        delete: false,
      },
      branch: {
        view: false,
        edit: false,
      },
      report: {
        view: false,
        edit: false,
      },
    },
    tax: {
      view: false,
      add: false,
      edit: false,
      delete: false,
    },
    state: {
      view: false,
      edit: false,
    },
  },
  claims: {
    view: false,
    caseManagement: {
      view: false,
      viewCasePendingStatus: false,
      bulkAssignment: false,
      export: false,
      case: {
        caseDocuments: false,
        view: false,
        add: false,
        edit: false,
        delete: false,
        uploadFile: false,
        holdCase: false,
        sendBack: false,
        reopenCase: false,
        withdrawCase: false,
        caseRecord: {
          view: false,
          edit: false,
          caseIdEdit: false,
          caseIdPasteOnly: false,
        },
        preQC: {
          view: false,
          edit: false,
        },
        assignment: {
          view: false,
          edit: false,
          assignInvestigator: false,
          withdrawInvestigator: false,
          expense: {
            view: false,
            add: false,
            edit: false,
            delete: false,
          },
        },
        postFieldQC: {
          view: false,
          edit: false,
          penalty: {
            view: false,
            edit: false,
          },
          expense: {
            view: false,
            edit: false,
            delete: false,
          },
        },
        assignReportWriter: {
          view: true,
          assign: true,
        },
        reportWriter: {
          view: false,
          edit: false,
          downloadDocuments: false,
          downloadReport: false,
          // assignReportWriter: false,
          withdrawReportWriter: false,
        },
        reportQC: {
          view: false,
          edit: false,
        },
        submission: {
          view: false,
          edit: false,
        },
        caseNote: {
          view: false,
          add: false,
          edit: false,
          delete: false,
        },
        caseStatus: {
          view: false,
        },
        caseReopenHistory: {
          view: false,
        },
      },
    },
    caseExpense: {
      view: false,
      edit: false,
      delete: false,
      export: false,
    },
    uploadClaims: {
      view: false,
      edit: false,
    },
    hardCopy: {
      edit: false,
      view: false,
      delete: false,
      export: false,
      claimsMetrics: false,
      hardCopyReceive: false,
    },
  },
  accounts: {
    view: false,
    clientBilling: {
      view: false,
      add: false,
      edit: false,
      delete: false,
      export: false,
      counts: false,
      paymentReceive: false,
      cancelInvoice: false,
    },
    investigatorPayout: {
      view: false,
      add: false,
      edit: false,
      delete: false,
      export: false,
      counts: false,
    },
    reportWriterPayout: {
      view: false,
      add: false,
      edit: false,
      delete: false,
      export: false,
      counts: false,
    },
    creditNote: {
      view: false,
      delete: false,
      export: false,
      counts: false,
      paymentRefund: false,
    },
  },
  analytics: {
    view: false,
    caseDashboard: {
      view: false,
      cases: false,
      tatMetrics: false,
      delayedInvestigation: false,
      financialMetrics: false,
      yearOverYearCaseGrowth: false,
    },
    investigatorDashboard: {
      view: false,
      statistics: false,
      penalizedInvestigators: false,
      top5PenalizedInvestigators: false,
      penalizedAmount: false,
      penalizedVsNonPenalized: false,
      incomeVsPenalty: false,
      top5PenaltyReasons: false,
      top5NonPenalzedInvestigators: false,
      todaysPenalizedCases: false,
    },
    incomeVsExpenseDashboard: {
      view: false,
      incomeExpenseOverview: false,
      yearOverYearIncomeGrowth: false,
      incomeVsExpenseTrend: false,
      topClients: false,
      yearOverYearExpenseGrowth: false,
    },
  },
  company: {
    view: false,
    companyDetails: {
      view: false,
      edit: false,
    },
    bankDetails: {
      view: false,
      edit: false,
    },
  },
  settings: {
    view: false,
    fileConfiguration: {
      view: false,
      edit: false,
    },
    // charges: {
    //   view: false,
    //   // investigation: {
    //   //   view: false,
    //   //   edit: false,
    //   // },
    //   reporting: {
    //     view: false,
    //     edit: false,
    //   },
    //   // clientBilling: {
    //   //   view: false,
    //   //   edit: false,
    //   // },
    // },
    privacyPolicy: {
      view: false,
      edit: false,
    },
    termsConditions: {
      view: false,
      edit: false,
    },
  },
  reports: {
    view: false,
  },
};
