import { ModuleConfig } from "@/types/admin.types";

export const BRAND_MODULES: ModuleConfig[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    path: "/brand/dashboard",
    icon: "LayoutDashboard",
    adminTypes: ["brand"],
  },
  {
    id: "team",
    name: "Team",
    path: "/brand/team",
    icon: "Users",
    adminTypes: ["brand"],
    children: [
      {
        id: "users",
        name: "Users",
        path: "/brand/team/user",
        icon: "User",
        adminTypes: ["brand"],
      },
      {
        id: "roles",
        name: "Roles",
        path: "/brand/team/role",
        icon: "Shield",
        adminTypes: ["brand"],
      },
    ],
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    path: "/brand/whatsapp",
    icon: "MessageCircle",
    adminTypes: ["brand"],
  },
  {
    id: "templates",
    name: "Templates",
    path: "/brand/templates",
    icon: "FileText",
    adminTypes: ["brand"],
  },
  {
    id: "webhooks",
    name: "Webhooks",
    path: "/brand/webhooks",
    icon: "Webhook",
    adminTypes: ["brand"],
  },
  {
    id: "billing",
    name: "Billing",
    path: "/brand/billing",
    icon: "CreditCard",
    adminTypes: ["brand"],
  },
  {
    id: "compliance",
    name: "Compliance",
    path: "/brand/compliance",
    icon: "FileCheck",
    adminTypes: ["brand"],
  },
  {
    id: "settings",
    name: "Settings",
    path: "/brand/settings",
    icon: "Settings",
    adminTypes: ["brand"],
  },
  {
    id: "danger-zone",
    name: "Danger Zone",
    path: "/brand/danger-zone",
    icon: "AlertTriangle",
    adminTypes: ["brand"],
  },
  {
    id: "notifications",
    name: "Notifications",
    path: "/brand/notifications",
    icon: "Bell",
    adminTypes: ["brand"],
  },
];

export const AGENCY_MODULES: ModuleConfig[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    path: "/agency/dashboard",
    icon: "LayoutDashboard",
    adminTypes: ["agency"],
  },
  {
    id: "brands",
    name: "Brands",
    path: "/agency/brands",
    icon: "Building",
    adminTypes: ["agency"],
  },
  {
    id: "team",
    name: "Team",
    path: "/agency/team",
    icon: "Users",
    adminTypes: ["agency"],
    children: [
      {
        id: "users",
        name: "Users",
        path: "/agency/team/user",
        icon: "User",
        adminTypes: ["agency"],
      },
      {
        id: "roles",
        name: "Roles",
        path: "/agency/team/role",
        icon: "Shield",
        adminTypes: ["agency"],
      },
    ],
  },
  {
    id: "billing",
    name: "Billing",
    path: "/agency/billing",
    icon: "CreditCard",
    adminTypes: ["agency"],
  },
  {
    id: "whitelabel",
    name: "Whitelabel",
    path: "/agency/whitelabel",
    icon: "Palette",
    adminTypes: ["agency"],
  },
  {
    id: "reports",
    name: "Reports",
    path: "/agency/reports",
    icon: "BarChart",
    adminTypes: ["agency"],
  },
  {
    id: "templates",
    name: "Templates",
    path: "/agency/templates",
    icon: "FileText",
    adminTypes: ["agency"],
  },
  {
    id: "compliance",
    name: "Compliance",
    path: "/agency/compliance",
    icon: "FileCheck",
    adminTypes: ["agency"],
  },
  {
    id: "settings",
    name: "Settings",
    path: "/agency/settings",
    icon: "Settings",
    adminTypes: ["agency"],
  },
  {
    id: "danger-zone",
    name: "Danger Zone",
    path: "/agency/danger-zone",
    icon: "AlertTriangle",
    adminTypes: ["agency"],
  },
];

export const OWNER_MODULES: ModuleConfig[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    path: "/owner/dashboard",
    icon: "LayoutDashboard",
    adminTypes: ["owner"],
  },
  {
    id: "team",
    name: "Team",
    path: "/owner/team",
    icon: "Users",
    adminTypes: ["owner"],
    children: [
      {
        id: "users",
        name: "Users",
        path: "/owner/team/user",
        icon: "User",
        adminTypes: ["owner"],
      },
      {
        id: "roles",
        name: "Roles",
        path: "/owner/team/role",
        icon: "Shield",
        adminTypes: ["owner"],
      },
    ],
  },
  {
    id: "agencies",
    name: "Agencies",
    path: "/owner/agencies",
    icon: "Briefcase",
    adminTypes: ["owner"],
  },
  {
    id: "brands",
    name: "Brands",
    path: "/owner/brands",
    icon: "Building",
    adminTypes: ["owner"],
  },
  {
    id: "billing",
    name: "Billing",
    path: "/owner/billing",
    icon: "CreditCard",
    adminTypes: ["owner"],
  },
  {
    id: "subscription",
    name: "Subscription",
    path: "/owner/subscription",
    icon: "Calendar",
    adminTypes: ["owner"],
  },
  {
    id: "coupon",
    name: "Coupon",
    path: "/owner/coupon",
    icon: "Ticket",
    adminTypes: ["owner"],
  },
  {
    id: "faq",
    name: "FAQ",
    path: "/owner/faq",
    icon: "HelpCircle",
    adminTypes: ["owner"],
  },
  {
    id: "master",
    name: "Master Data",
    path: "/owner/master",
    icon: "Database",
    adminTypes: ["owner"],
  },
  {
    id: "features",
    name: "Features",
    path: "/owner/features",
    icon: "Zap",
    adminTypes: ["owner"],
  },
  {
    id: "monitoring",
    name: "Monitoring",
    path: "/owner/monitoring",
    icon: "Activity",
    adminTypes: ["owner"],
  },
  {
    id: "logs",
    name: "Logs",
    path: "/owner/logs",
    icon: "FileText",
    adminTypes: ["owner"],
  },
  {
    id: "config",
    name: "Config",
    path: "/owner/config",
    icon: "Settings",
    adminTypes: ["owner"],
  },
  {
    id: "emergency",
    name: "Emergency",
    path: "/owner/emergency",
    icon: "AlertOctagon",
    adminTypes: ["owner"],
  },
  {
    id: "templates",
    name: "Templates",
    path: "/owner/templates",
    icon: "LayoutTemplate",
    adminTypes: ["owner"],
  },
];
